/control/verbose 2
/vis/open OGLIX
/vis/viewer/set/style wireframe
/vis/drawVolume
/vis/viewer/set/viewpointThetaPhi 30 15 deg
/vis/viewer/set/projection perspective 30 deg 
/vis/viewer/zoom 1
# coordinate axes:
#     x-axis:red,  y-axis:green,  z-axis:blue
/vis/scene/add/axes            8 -6 -6 1 cm
/tracking/storeTrajectory 2
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate

/run/beamOn 1

/control/alias phi 0
/control/loop movie.loop theta 0 360 1
